services:
  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wp
    build: ./srcs/requirements/wordpress/.
    env_file: ./.env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_USER_EMAIL: ${DB_USER_EMAIL}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PREFIX: ${DB_PREFIX}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb/.
    env_file:
      - ./.env
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always

volumes:
  wp_data:
  db_data:

networks:
  inception:
    driver: bridge
